TestNG Homework
osukhorukova/AQA pull request #1
Opened 2024-03-04 04:51 UTC by osukhorukova

Написала тесты для процедур деления: 

1. int/int
2. int/double
3. int/0
4. double/double
5. double/int
6. double/0

2024-03-04 12:00 UTC, wildpioneer requested changes

2024-03-04 12:00 UTC, wildpioneer commented on src/test/java/CalcTest.java
> +
Отсутствуют тесты с использованием следующих атрибутов:
1. enable
2. description
3. invocationCount, invocationTimeOut, threadPoolSize
4. timeOut
5. expectedExceptions
6. dependsOnMethods
7. groups
8. @Parameters
9. priority
10. retryAnalyzer

2024-03-04 12:34 UTC, osukhorukova commented on src/test/java/CalcTest.java
> +
Привет! 
я упустила тот момент, что нужно использовать разнообразные атрибуты при выполнении домашнего задания, исправлю, спасибо)

2024-03-10 16:24 UTC, osukhorukova commented on src/test/java/CalcTest.java
> +
Пушнула правки. Добавила атрибуты: 

1. priority
2. groups
3. invocationCount, invocationTimeOut
4. enable
5. description
6. timeOut
7. dependsOnMethods
8. retryAnalyzer

Атрибуты `expectedExceptions` и `threadPoolSize` были использованы и в первоначальной версии домашнего задания (либо я что-то не так понимаю)

2024-03-10 22:09 UTC, wildpioneer commented
Проверено

2024-03-10 22:09 UTC, closed without merging