Selenium Driver Homework
osukhorukova/AQA pull request #2
Opened 2024-03-04 12:32 UTC by osukhorukova

2024-03-10 22:11 UTC, wildpioneer requested changes

2024-03-10 22:11 UTC, wildpioneer commented on src/test/java/ElectricWarmFloorCalcTest.java
> +        Thread.sleep(2000);
Зачем ожидание по 2 секунды после каждого действия?

2024-03-10 22:11 UTC, wildpioneer commented on src/test/java/ElectricWarmFloorCalcTest.java
> +
Лишняя пустая строка перед закрытием метода

2024-03-10 22:11 UTC, wildpioneer commented on src/test/java/ElectricWarmFloorCalcTest.java
> +
Лишняя пустая строка перед закрытием метода

2024-03-16 19:35 UTC, osukhorukova commented on src/test/java/ElectricWarmFloorCalcTest.java
> +        Thread.sleep(2000);
Я ставила ожидания, чтобы можно было визуально отследить прогресс прохождения тестов. Убрать?

2024-03-16 19:49 UTC, osukhorukova commented on src/test/java/ElectricWarmFloorCalcTest.java
> +
Пушнула правки: 

1. убрала ожидания 
2. убрала лишние пустые строки

2024-03-25 14:39 UTC, wildpioneer commented on src/test/java/ElectricWarmFloorCalcTest.java
> +        Thread.sleep(2000);
Да

2024-03-25 14:39 UTC, wildpioneer commented
Проверено

2024-03-25 14:39 UTC, closed without merging